---
sidebar: sidebar 
permalink: scpivs44_how_restore_operations_are_performed.html 
keywords:  
summary: 在VMFS環境中、SnapCenter VMware vSphere的VMware vSphere的《Sesf2外掛程式》使用Storage vMotion來執行複製和掛載作業、以執行還原作業。對於NFS環境、外掛程式使用原生ONTAP 的「僅供參考的單一檔案SnapRestore 」（SFSR）、為大多數的還原作業提供更高的效率。 
---
= 如何執行還原作業
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


在VMFS環境中、SnapCenter VMware vSphere的VMware vSphere的《Sesf2外掛程式》使用Storage vMotion來執行複製和掛載作業、以執行還原作業。對於NFS環境、外掛程式使用原生ONTAP 的「僅供參考的單一檔案SnapRestore 」（SFSR）、為大多數的還原作業提供更高的效率。下表列出如何執行還原作業。

|===
| 還原作業 | 在ONTAP NFS環境中使用SSRSSFSR執行 | 在NFS環境中使用Clone和Mount with Storage VMotion執行 | 在VMFS環境中使用Clone和Mount with Storage VMotion執行 


| 從主要備份還原VM和VMDK | 是的 |  | 是的 


| 從次要備份還原VM和VMDK | 是的 |  | 是的 


| 從主要備份還原刪除的VM和VMDK | 是的 |  | 是的 


| 從次要備份還原刪除的VM和VMDK |  | 是的 | 是的 


| 從VM一致的主要備份還原VM和VMDK | 是的 |  | 是的 


| 從VM一致的次要備份還原VM和VMDK |  | 是的 | 是的 
|===
在NFS和VMFS環境中使用複製和掛載作業（而非Storage vMotion）來執行客體檔案還原作業。


IMPORTANT: 在還原作業期間、您可能會遇到「Host unresolved volume is null」（主機未解析磁碟區為null）或「調用選擇控制器上的預先還原時發生例外狀況...將複製的LUN掛載為資料存放區時發生錯誤...」 當VMware vCenter外掛程式嘗試重新簽署實體複本時、就會發生這種情況SnapCenter 。由於VMware的限制、SnapCenter 在進階ESXi組態中、VMware插件無法控制自動重新簽名值。

如需錯誤的詳細資訊、請參閱｛link with底線｝[KB文章：選擇控制器實體複製或還原失敗、並顯示錯誤「主機未解析的磁碟區為null」。
